/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions.$decisionId'

const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/mirror': typeof MirrorRoute
  '/score': typeof ScoreRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/mirror': typeof MirrorRoute
  '/score': typeof ScoreRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/mirror': typeof MirrorRoute
  '/score': typeof ScoreRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feed' | '/mirror' | '/score' | '/decisions/$decisionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed' | '/mirror' | '/score' | '/decisions/$decisionId'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/mirror'
    | '/score'
    | '/decisions/$decisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  MirrorRoute: typeof MirrorRoute
  ScoreRoute: typeof ScoreRoute
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  MirrorRoute: MirrorRoute,
  ScoreRoute: ScoreRoute,
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
